### ISSUE TITLE
Develop the landing page

### ISSUE THREAD

**Issue by Ogirimah** [zuri-training/Team-65-Favicon-gen#17]
This should be developed without the header and footer, as that will be done by another member of the team.

The deadline for the completion of this is 8pm, Friday, 5th of August, 2022.

The development should be done in accordance with the design on [this Figma board](https://www.figma.com/file/FrTnphzP59CDzzn1A5HuRV/Favicons-Developers-Version?node-id=0%3A1)

And the images you will need has been uploaded to a Google drive and [this link](https://drive.google.com/drive/folders/1U56ddJb8FJxM4795nN9yVq2H9zF6uNT0?usp=sharing) allows you to access and download the images

**Comment by Ogirimah** [comment]
Please remove the SVG codes from the HTML, and only reference them using the <img> tag and style them in the .css file.
This will allow us to easily work with the code when merging with backend. thanks

**Comment by Ogirimah** [comment]
Hi Timi, Please develop the responsive mobile version of this issue using media query. We are running out of time. So deadline is 6am tomorrow morning. 
Link to the Figma board for guidance is https://www.figma.com/file/KOIzFZALBUK7Hrk8S7qxmL/Team-65_Favicon-Gen---Figma-Board?node-id=1228%3A17299

**Comment by timmy3000** [comment]
![Image](https://user-images.githubusercontent.com/66499629/184365643-c5c81577-b080-4f88-900a-7634a0f9cbb8.png)
![Image](https://user-images.githubusercontent.com/66499629/184365645-799eb1ce-2997-4e66-ac6a-e81604d4997e.png)
![Image](https://user-images.githubusercontent.com/66499629/184365646-8577e792-f7dd-42e5-84d5-449b88c892fa.png)
