### ISSUE TITLE
Develop the SignUp page

### ISSUE THREAD

**Issue by Ogirimah** [zuri-training/Team-65-Favicon-gen#18]
This should be developed without the header and footer, as that will be done by another member of the team.

The deadline for the completion of this is 8pm, Friday, 5th of August, 2022.

The development should be done in accordance with the design on [this Figma board](https://www.figma.com/file/FrTnphzP59CDzzn1A5HuRV/Favicons-Developers-Version?node-id=0%3A1)

And the images you will need has been uploaded to a Google drive and [this link](https://drive.google.com/drive/folders/1qLA631GijnxNsdoHGPG6ohjQ0q8KzJ4O?usp=sharing) allows you to access and download the images

**Comment by Toby2507** [comment]
Please add the mobile design provided in the [Figma board](https://www.figma.com/file/KOIzFZALBUK7Hrk8S7qxmL/Team-65_Favicon-Gen---Figma-Board?node-id=1%3A8)

**Comment by digitalnobsx** [comment]
Added mobile design to sign-up page.
