### ISSUE TITLE
Develop the SignIn page

### ISSUE THREAD

**Issue by Ogirimah** [zuri-training/Team-65-Favicon-gen#19]
This should be developed without the header and footer, as that will be done by another member of the team.

The deadline for the completion of this is 8pm, Friday, 5th of August, 2022.

The development should be done in accordance with the design on [this Figma board](https://www.figma.com/file/FrTnphzP59CDzzn1A5HuRV/Favicons-Developers-Version?node-id=0%3A1)

And the images you will need has been uploaded to a Google drive and [this link](https://drive.google.com/drive/folders/1H5ysvfYocxcPWvVIw_f7uz35PDK1KF2z?usp=sharing) allows you to access and download the images

**Comment by stylebytemi** [comment]
Done https://github.com/zuri-training/Team-65-Favicon-gen/pull/23#issue-1329991618
