### ISSUE TITLE
Develop the header and footer

### ISSUE THREAD

**Issue by Ogirimah** [zuri-training/Team-65-Favicon-gen#22]
This should be developed without the header and footer, as that will be done by another member of the team.

The deadline for the completion of this is 8pm, Friday, 5th of August, 2022.

The development should be done in accordance with the design on [this Figma board](https://www.figma.com/file/FrTnphzP59CDzzn1A5HuRV/Favicons-Developers-Version?node-id=0%3A1)

And the images you will need has been uploaded to a Google drive and [this link](https://drive.google.com/drive/folders/1AJndm8KBD4BhaRwAAvEZWhH45ibymp2N?usp=sharing) allows you to access and download the images

**Comment by Guddyade** [comment]
I'm yet unable to get the js aspect done. Mainly the css and html aspect of the sign-in page was done
