### ISSUE TITLE
Mobile landing page design

### ISSUE THREAD

**Issue by Ogirimah** [zuri-training/Team-65-Favicon-gen#26]
Design the mobile version of the already completed desktop design

**Comment by Tolueen22** [comment]
On-going. Would be completed in the next 2hours

**Comment by Motolani1815** [comment]
Currently working on it. My part of the design would be ready in the next 2 hours.

**Comment by Red-April0334** [comment]
Ongoing

**Comment by Fidelis19** [comment]
Mobile version is done, and included in the submitted figma link

**Comment by simiann-777** [comment]
I've completed my part of the design

**Comment by Tolueen22** [comment]
> On-going. Would be completed in the next 2hours

Task completed and delivered. So sorry for the late update
