### ISSUE TITLE
Mobile SignIn page and SignUp page design

### ISSUE THREAD

**Issue by Ogirimah** [zuri-training/Team-65-Favicon-gen#27]
Design the mobile version of the already completed desktop design

**Comment by Tamunololia** [comment]
Done and concluded

**Comment by nightwayve** [comment]
> Done and concluded

Done

**Comment by nightwayve** [comment]
> Design the mobile version of the already completed desktop design

completed

**Comment by Bukolagrace** [comment]
It has been designed.

**Comment by Red-April0334** [comment]
Done
