### ISSUE TITLE
Cleaning up of figma work space and proper labelling

### ISSUE THREAD

**Issue by Ogirimah** [zuri-training/Team-65-Favicon-gen#45]
- [x] Clean up the main work and mood board
- [x] Clean up page 1 and Page 4
- [x] Clean up Group 2 style guide  and Group 2 main work
- [x] Clean up Group 3 style guide
- [x] Clean up Group 4 style guide
- [x] Clean up Group 3 main work

**Comment by nightwayve** [comment]
> * Clean up Group 2 style guide  and Group 2 main work

I have cleaned up Group 2 style guide and Group 2 main work

**Comment by Red-April0334** [comment]
I have arranged and cleaned up group 3 main work. 

>

**Comment by Bukolagrace** [comment]
I have sorted and arranged pages 1 and 4 workspace.

**Comment by Of-Momo** [comment]
The group 3 style guide page and the group 4 main work page has been sorted and arranged

**Comment by Jaylucia** [comment]
I have sorted and arranged group 4 style guide
