### ISSUE TITLE
User Persona and Response Arrangement

### ISSUE THREAD

**Issue by Ogirimah** [zuri-training/Team-65-Favicon-gen#47]
- [x] Survey response arrangement
- [x] User persona design

**Comment by Jaylucia** [comment]
User persona design completed

**Comment by nightwayve** [comment]
> * [ ]  Survey response arrangement
> * [ ]  User persona design

survey response arrangement completed

**Comment by Red-April0334** [comment]
> * [ ]  Survey response arrangement
> * [ ]  User persona design

Task accomplished.
