### ISSUE TITLE
Create the digital lofi wireframe

### ISSUE THREAD

**Issue by Ogirimah** [zuri-training/Team-65-Favicon-gen#49]

**Comment by Jaylucia** [comment]
Digital lofi wireframe creation is complete

**Comment by LadyPriye** [comment]
I collaborated with @Jaylucia and @Of-Momo to design the low-fidelity wireframes for ICONATOR. 

https://www.figma.com/file/6nwFE1sMy5bvyy5RDkrOkp/Lofi-Iconator?node-id=0%3A1

**Comment by Of-Momo** [comment]
The digital low-fidelity wireframe has been created

https://www.figma.com/file/6nwFE1sMy5bvyy5RDkrOkp/Lofi-Iconator?node-id=0%3A1
