### ISSUE TITLE
Create the style guide

### ISSUE THREAD

**Issue by Ogirimah** [zuri-training/Team-65-Favicon-gen#51]

**Comment by Jaylucia** [comment]
Style guide creation is complete

**Comment by LadyPriye** [comment]
I collaborated with @Jaylucia and @Of-Momo to create the Style Guide to be used in the designs for our Project (ICONATOR). 
https://www.figma.com/file/sdECVMRVcdTaiwRA8SrKpi/Style-Guide-and-Mood-Board-Iconator?node-id=1%3A1730

**Comment by Of-Momo** [comment]
Style guide creation has been completed
