### ISSUE TITLE
Document the whole UX process for Iconator

### ISSUE THREAD

**Issue by Ogirimah** [zuri-training/Team-65-Favicon-gen#57]

**Comment by Bukolagrace** [comment]
Here is the documentation file link to the UX process https://doc-0g-4g-docs.googleusercontent.com/docs/securesc/2r7kgoo38jgs149l997ovpjtn367dvjp/gfhkipaiqba83qvatrvvpgg189ajh7ta/1660140975000/04699931123505393392/08429578409685460517/1ZN39KQLYCKieKyyQvB9FvZEUODqYQFlY?e=download&authuser=0

**Comment by Bukolagrace** [comment]
Here is the documentation file link to the UX process https://doc-0g-4g-docs.googleusercontent.com/docs/securesc/2r7kgoo38jgs149l997ovpjtn367dvjp/gfhkipaiqba83qvatrvvpgg189ajh7ta/1660140975000/04699931123505393392/08429578409685460517/1ZN39KQLYCKieKyyQvB9FvZEUODqYQFlY?e=download&authuser=0

**Comment by Fidelis19** [comment]
I proof read and arranged the document while my team mates worked on the documentation

**Comment by Bukolagrace** [comment]
Here is the documentation file link to the UX process https://docs.google.com/presentation/d/1ZN39KQLYCKieKyyQvB9FvZEUODqYQFlY/edit?usp=sharing&ouid=116200026049709901124&rtpof=true&sd=true

**Comment by Tamunololia** [comment]
I worked on documenting the user experience. Below attached is a link to the documentation.
https://docs.google.com/presentation/d/1ZN39KQLYCKieKyyQvB9FvZEUODqYQFlY/edit?usp=sharing&ouid=116200026049709901124&rtpof=true&sd=true
