### ISSUE TITLE
Conduct survey and come up with the analysis

### ISSUE THREAD

**Issue by Ogirimah** [zuri-training/Team-65-Favicon-gen#59]

**Comment by Bukolagrace** [comment]
The survey has been conducted and analyzed.

**Comment by Tamunololia** [comment]
Survey done.
I created the survey forms using Google forms. Attached is the Google form link.
https://forms.gle/hjXXfGvuBmkgBZJo8

**Comment by Bukolagrace** [comment]
Link to the analysis derived from the survey https://www.figma.com/file/Q4r77ap3wY5vMbw4FPN5YW/ICONATOR-RESEARCH-ANALYSIS?node-id=0%3A1

**Comment by Bukolagrace** [comment]
Link to survey analysis https://www.figma.com/file/Q4r77ap3wY5vMbw4FPN5YW/ICONATOR-RESEARCH-ANALYSIS?node-id=0%3A1
