### ISSUE TITLE
Come up with the Research plan and Questions. Also source correspondence for the unmoderated survey

### ISSUE THREAD

**Issue by Ogirimah** [zuri-training/Team-65-Favicon-gen#60]

**Comment by nightwayve** [comment]
task done

**Comment by Bukolagrace** [comment]
Here is the link to the research conducted.  https://www.figma.com/file/Q7sAPR6Altkdc9M4UnSfwN/Iconator-Research?node-id=0%3A1

**Comment by Bukolagrace** [comment]
Here is the link to the Research plan https://docs.google.com/document/d/1mRUsG2okvx8mWq3c2VX1a0Eu9lwa8I7It_O46YQSJ6Q/edit?usp=drivesdk
