### ISSUE TITLE
Create hifi mobile

### ISSUE THREAD

**Issue by Ogirimah** [zuri-training/Team-65-Favicon-gen#62]

**Comment by Fidelis19** [comment]
This has been done, i worked on the landing page and the about us page and rest password pages. My team mates worked on the rest of the screens

**Comment by Motolani1815** [comment]
This task has been done. I created the reset password page, create favicon page, as well as the log in page

**Comment by simiann-777** [comment]
This task is completed. I worked with some other team members on this task. I created the landing page, I monitored the spacers and alignments.

**Comment by simiann-777** [comment]
https://www.figma.com/file/oNEE1MXe1vBHUsaem55CfX

Link to the Figma board

**Comment by Tolueen22** [comment]
User profile, Generate favicon page, contact us page the preview page were created
https://www.figma.com/file/oNEE1MXe1vBHUsaem55CfX/ICONATOR-(Group-65)?node-id=1%3A8
