### ISSUE TITLE
Create hifi wireframes for design

### ISSUE THREAD

**Issue by Ogirimah** [zuri-training/Team-65-Favicon-gen#69]

**Comment by Tolueen22** [comment]
hi-fi designs for all screens completed.
https://www.figma.com/file/oNEE1MXe1vBHUsaem55CfX/ICONATOR-(Group-65)?node-id=1%3A8

**Comment by Fidelis19** [comment]
I created the landing page, the about us page, check out transition pages and the some reset password process screens

**Comment by Fidelis19** [comment]
all done

**Comment by Motolani1815** [comment]
This part is all done
