### ISSUE TITLE
Create FAQ page

### ISSUE THREAD

**Issue by Toby2507** [zuri-training/Team-65-Favicon-gen#71]
- [ ] Create the mobile and desktop design for the faq page as depicted on the Figma board
- [ ] Demo JS project for the faq accordion - [project zip file](https://drive.google.com/file/d/1k2ubYbNqy8gww_AvzOeoYk1-2AS9tatp/view?usp=sharing)
- [ ] Use the images provided [here](https://drive.google.com/file/d/1V8LqyWcLY_zEIVLVMBPCgpBMnsls-Yw3/view?usp=sharing) in the faq_page folder

**Comment by Ogirimah** [comment]
Please try to finish and submit before 10pm tonight as we are to submit the project tomorrow.
The Figma board to use is https://www.figma.com/file/KOIzFZALBUK7Hrk8S7qxmL/Team-65_Favicon-Gen---Figma-Board?node-id=1228%3A17299
