### ISSUE TITLE
Create reset password page

### ISSUE THREAD

**Issue by Toby2507** [zuri-training/Team-65-Favicon-gen#72]
1. Create the reset password mobile and desktop page using the design on the Figma board
2. Use the image supplied [here](https://drive.google.com/file/d/1V8LqyWcLY_zEIVLVMBPCgpBMnsls-Yw3/view?usp=sharing) in the reset_password_page folder

**Comment by Ogirimah** [comment]
Please do this and push it to before 10pm tonight, as we are to submit the project tomorrow
